cargo-features = ["strip"]

[workspace]
members = [
  "cli",
  "core",
]

[profile.release]
lto = true
codegen-units = 1
incremental = false
# Unless proper benchmarks show it's worth the tradeoff this remains off
# opt-level = "z"
strip = "symbols"
