[package]
name = "nyaa_gui"
version = "0.1.0"
authors = ["Federico Morrone <flickmor@gmail.com>"]
edition = "2018"

[dependencies]
iced = "0.2.0"
nyaa_core = { path = "../core", version = "0.1" }

[[bin]]
name = "nyaa_gui"
path = "main.rs"
doc = false
